const API_URL = 'https://script.google.com/macros/s/AKfycbxemngF4ASnvsbx6hDrrQKiGIzDAGg2xib7RlYeo_hu3eCi0jNceiRYmS83vuQ1H9Cb/exec'; 
const state={sessions:[]}; const $=s=>document.querySelector(s);
function hex(b){return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function credential(password,salt){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:600000,hash:'SHA-256'},k,256);return hex(b)}
async function api(action,payload={}){if(!API_URL)throw Error('Configure a URL do Apps Script no app.js.');const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});const j=await r.json();if(!j.ok)throw Error(j.error||'Não foi possível concluir.');return j.data}
function hydrate(data){if(!data)return;const name=data.user?.name;if(name)$('#userName').textContent=name.split(' ')[0];state.sessions=data.sessions||[];const done=state.sessions.filter(s=>s.status==='done');$('#monthWorkouts').textContent=done.length||18}
function showDashboard(data){if(data?.token)localStorage.setItem('meu_treino_token',data.token);$('#auth').style.display='none';$('.app').style.display='block';hydrate(data)}
async function loadState(){const token=localStorage.getItem('meu_treino_token');if(!token)return;try{const data=await api('state',{token});showDashboard(data)}catch(_){localStorage.removeItem('meu_treino_token')}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#authMessage');msg.textContent='Entrando...';try{const email=$('#email').value.trim().toLowerCase();const salt=await api('salt',{email});const data=await api('login',{email,credential:await credential($('#password').value,salt.salt)});showDashboard(data)}catch(err){msg.textContent=err.message}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');loadState();
